name: Build megasdkbase image

on:
  workflow_dispatch
jobs:
  BuildBase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: token
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockers/Dockerfile.alt
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/ytubeupx/megarestbase:latest
          secr |
name: Build megasdkbase image

on:
  workflow_dispatch
jobs:
  BuildBase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: token
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: ghcr.io/tonmoyislam/debbuild:latest
 
